### PR TITLE
New updates : Mhousse1247

### PR DESCRIPTION
**Pull request by mhousse1247**
*Street Map Runtime Module:
-Street Map Actor
-Collision Support
-Navigation Support
-Some bugs fixes

*Added Street Map Editor Module:
- Street Map Details Customization: Build/Rebuild Button, Clear Mesh
Button, Create Static Mesh Asset Button, And Mesh info section.
- Street Map Slate Style : Class Editor Icons/Thumbnails

* Content Folder :
- StreetMapDefaultMaterial (Material Asset)
- Icons(PNG)

*Engine version 4.14.1

### CODE REVIEW

**Comment by MikeFricker** [comment]
Awesome!  I'll try this out later this evening and look over the code.  Thanks so much for adding these new features.

**Comment by mhousse1247** [comment]
You're welcome !
Sorry I made the first commit with a wrong account , I fixed it in the last one !

**Comment by MikeFricker** [comment]
Was just playing around with this for a bit.  Overall looks great!  A few minor suggestions -- I can make these changes if you aren't able to get around to them:

1)  We can probably combine the StreetMapImporting and StreetMapEditor modules just to keep things simple.  I'd move the importing code into your new editor module.

2)  Because the new buttons for generating the mesh are under an 'Advanced' drop down, I actually didn't notice them at first and had to go looking for them.  Also, the mesh isn't visible at all until the user clicks "Build Mesh" at least once, which was a bit confusing.  I think we either need to make those buttons visible by default, or automatically build the mesh with default settings initially, like it did before.  Just so the user can see something after assigning the asset, right?  Actually, I wonder if we should just automatically rebuild the mesh after any of those new properties change, similarly to how if the "StreetMap" property is updated on the component.  Any thoughts?

3)  We'll need to get the 'Getting Started' page updated before we can merge it in.  Mainly to tell the user about the new options for tweaking stuff, and how to manually rebuild the mesh.

**Comment by mhousse1247** [comment]
Yeah , I think it's a better idea to combine the two , and no problem I will do it.

For the button I setted Initially Collapsed false , but now it seems to not be sufficient when I exposed settings structs. So I move them to the top of "StretMap" category to be visible from the begening .

I found that it is a litle bit annoying to rebuild the mesh with any minor property change espcially while rebuilding mesh & collsion + updading navigation.

This is way I let Build/Rebuil/Clear to be on demande , only Collision & Navigation are force to update when a collision property changed

I  will also notify the new changes in the readme file.

Sorry , for Mac , I think you can check from your side because I don't own one !

**Comment by mhousse1247** [comment]
Hey Mike,

Here are the new updates :

- Added StreetMapActorFactory to spawn a new StreetMapActor when a StreetMap Data
  Asset is droped in the viewport
- StreetMapImporting and StreetMapEditor modules are now combined.
-Details Costumization buttons are now visible on the top of 'StreetMap' Category.
- Updated ReadMe file

**Comment by MikeFricker** [comment]
Nice update!!  I'll review and hopefully merge it all tomorrow after work.  Thanks again!  :)

**Comment by MikeFricker** [comment]
Awesome improvements.  Everything looked good.  I only fixed a minor compiler warning on Mac.   Thank you!

**Comment by mhousse1247** [comment]
Awesome ! Glad it helped :)
Now back to my '2D Extension Plugin' hope to share it soon with the community !

**Pull request merged**
