### PR TITLE
fix compile for 4.24

### PR DESCRIPTION
**Pull request by mbpictures**

### CODE REVIEW

**Comment by GamesUKStudios** [comment]
fantastic job dude really appreciate it saved me tons of hours for my game as it is a real life location game

**Comment by GamesUKStudios** [comment]
petty you can't use the landscape splines

**Comment by mbpictures** [comment]
Which landscape splines?

**Comment by GamesUKStudios** [comment]
image

**Comment by slevimk** [comment]
I managed to use the plugin in 4.25. When I play the character the map disappears.

**Comment by mbpictures** [comment]
Maybe you can try to create a static mesh from the map. This will hopefully prevent the map from disappearing

**Pull request closed without merging**
