### PR TITLE
Generate Landscape Actor beneath the OSM data

### PR DESCRIPTION
**Pull request by Hemofektik**
Hi,

the last couple of weeks I worked on the ability to genererate a Landscape Actor beneath the OSM data using Digital Elevation Model from online sources.
It is in a usable and bugfree state now. So before I continue to change more of the core compontents of the OSM Plugin I would like to get this version at least reviewed to know what is ok an what needs more work.

Any kind of feedback is appreciated.

Regards,
Richard

### CODE REVIEW

**Comment by MikeFricker** [comment]
Wow, thanks so much for the submission.   I haven't had a chance to look through the code properly, but I can tell you put a lot of work into it.  I really like the idea of generating landscape also!  I'll review it and send detailed feedback as soon as I can.  (Most likely sometime on the weekend.)  Thanks again for sharing.

**Comment by MikeFricker** [comment]
Just a heads up, I haven't had a chance to try out your new feature yet, but I plan to soon (next couple of days.)  The code looks great, I'll just have some minor feedback after I test it.

**Comment by RaceTheMaSe** [comment]
Awesome feature addition. Thank you so much, Richard! Your Todos look like this could lead to a great tool in the making. For adding splines to the landscape this [free RoadTool](https://forums.unrealengine.com/showthread.php?134508-Free-Simple-Road-Tool) from the forums gives a Blueprint example of how the spline is created from a "normal" spline (in case you didn't know already) ;-)

**Comment by Hemofektik** [comment]
I actually planned to use the Landscape Spline Meshes but this tool looks very powerful. Many thanks for the suggestion. I will definitely evaluate it.
I also saw your utymap projects and they have many overlaps with this one. The problem I have with them is that all the content is runtime generated, which allows not enough control of how the final result will look like. But this is a thing of personal taste and what you want to achieve and probably a topic to discuss somewhere else. :)

**Comment by MikeFricker** [comment]
Sorry sorry sorry, still haven't had a life moment for this one.  I've been sick for most of the last week.  And I'm traveling for 5 days after tomorrow.  I'm a horrible repository owner.  But I'll get to it, trust me.  I can't wait for this one.

**Comment by Hemofektik** [comment]
No worries, there are plenty of other unrelated tasks I can work on. :)

**Comment by RaceTheMaSe** [comment]
Mike, maybe you can also give feedback on a clean way of Landscape spline generation from OSM data and the hurdles you might see in it, like e.g. performance issues.

I imagine this could be developed to a roads & rail editor tab in the UI later.

**Comment by Hemofektik** [comment]
This morning I tried to create Landscape Spline Compontents programatically only to find out that they cannot be created outside of the landscape editor tool of the editor because of protected class members.
Any Ideas how to solve this without changing the engine code?

> I imagine this could be developed to a roads & rail editor tab in the UI later.

The LandscapeSpline Editor is already very powerful. It probably already supports many of the features needed to post edit the automatically created roads and railways. But lets see what we need when the roads and railways are there.

**Pull request closed without merging**
